# Generated by Django 2.2.6 on 2019-10-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicos',
            old_name='created_date',
            new_name='creatd_date',
        ),
    ]
